stages:
  - build

cmssw_compile:
  stage: build
  only:
    - master
  tags:
    - cvmfs
  variables:
    CMS_PATH: /cvmfs/cms.cern.ch
    CMSSW_RELEASE: CMSSW_9_4_4
  script:
    - set -ex
    - shopt -s expand_aliases
    - set +u && source ${CMS_PATH}/cmsset_default.sh; set -u
    - cmsrel ${CMSSW_RELEASE}
    - cd ${CMSSW_RELEASE}/src
    - mkdir -p BPHAnalysis
    - mv ${CI_PROJECT_DIR} ${CMSSW_RELEASE}/src/BPHAnalysis
    - cmsenv
    - scram b